// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InGamePacket.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "InGamePacket.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace InGamePacket {

namespace {

const ::google::protobuf::Descriptor* C_Move_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C_Move_reflection_ = NULL;
const ::google::protobuf::Descriptor* S_Move_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S_Move_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_InGamePacket_2eproto() {
  protobuf_AddDesc_InGamePacket_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "InGamePacket.proto");
  GOOGLE_CHECK(file != NULL);
  C_Move_descriptor_ = file->message_type(0);
  static const int C_Move_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, direction_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, duration_),
  };
  C_Move_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      C_Move_descriptor_,
      C_Move::default_instance_,
      C_Move_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, _has_bits_[0]),
      -1,
      -1,
      sizeof(C_Move),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, _internal_metadata_),
      -1);
  S_Move_descriptor_ = file->message_type(1);
  static const int S_Move_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, y_),
  };
  S_Move_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      S_Move_descriptor_,
      S_Move::default_instance_,
      S_Move_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, _has_bits_[0]),
      -1,
      -1,
      sizeof(S_Move),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_InGamePacket_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      C_Move_descriptor_, &C_Move::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      S_Move_descriptor_, &S_Move::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_InGamePacket_2eproto() {
  delete C_Move::default_instance_;
  delete C_Move_reflection_;
  delete S_Move::default_instance_;
  delete S_Move_reflection_;
}

void protobuf_AddDesc_InGamePacket_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022InGamePacket.proto\022\014InGamePacket\"-\n\006C_"
    "Move\022\021\n\tdirection\030\001 \002(\r\022\020\n\010duration\030\002 \002("
    "\r\"+\n\006S_Move\022\013\n\003uid\030\001 \002(\r\022\t\n\001x\030\002 \002(\r\022\t\n\001y"
    "\030\003 \002(\r", 126);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "InGamePacket.proto", &protobuf_RegisterTypes);
  C_Move::default_instance_ = new C_Move();
  S_Move::default_instance_ = new S_Move();
  C_Move::default_instance_->InitAsDefaultInstance();
  S_Move::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_InGamePacket_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_InGamePacket_2eproto {
  StaticDescriptorInitializer_InGamePacket_2eproto() {
    protobuf_AddDesc_InGamePacket_2eproto();
  }
} static_descriptor_initializer_InGamePacket_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int C_Move::kDirectionFieldNumber;
const int C_Move::kDurationFieldNumber;
#endif  // !_MSC_VER

C_Move::C_Move()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:InGamePacket.C_Move)
}

void C_Move::InitAsDefaultInstance() {
}

C_Move::C_Move(const C_Move& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:InGamePacket.C_Move)
}

void C_Move::SharedCtor() {
  _cached_size_ = 0;
  direction_ = 0u;
  duration_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C_Move::~C_Move() {
  // @@protoc_insertion_point(destructor:InGamePacket.C_Move)
  SharedDtor();
}

void C_Move::SharedDtor() {
  if (this != default_instance_) {
  }
}

void C_Move::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C_Move::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C_Move_descriptor_;
}

const C_Move& C_Move::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InGamePacket_2eproto();
  return *default_instance_;
}

C_Move* C_Move::default_instance_ = NULL;

C_Move* C_Move::New(::google::protobuf::Arena* arena) const {
  C_Move* n = new C_Move;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void C_Move::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<C_Move*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(direction_, duration_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool C_Move::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:InGamePacket.C_Move)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 direction = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &direction_)));
          set_has_direction();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_duration;
        break;
      }

      // required uint32 duration = 2;
      case 2: {
        if (tag == 16) {
         parse_duration:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &duration_)));
          set_has_duration();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:InGamePacket.C_Move)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:InGamePacket.C_Move)
  return false;
#undef DO_
}

void C_Move::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:InGamePacket.C_Move)
  // required uint32 direction = 1;
  if (has_direction()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->direction(), output);
  }

  // required uint32 duration = 2;
  if (has_duration()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->duration(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:InGamePacket.C_Move)
}

::google::protobuf::uint8* C_Move::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:InGamePacket.C_Move)
  // required uint32 direction = 1;
  if (has_direction()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->direction(), target);
  }

  // required uint32 duration = 2;
  if (has_duration()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->duration(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InGamePacket.C_Move)
  return target;
}

int C_Move::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_direction()) {
    // required uint32 direction = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->direction());
  }

  if (has_duration()) {
    // required uint32 duration = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->duration());
  }

  return total_size;
}
int C_Move::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint32 direction = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->direction());

    // required uint32 duration = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->duration());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C_Move::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const C_Move* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const C_Move>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C_Move::MergeFrom(const C_Move& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_direction()) {
      set_direction(from.direction());
    }
    if (from.has_duration()) {
      set_duration(from.duration());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void C_Move::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C_Move::CopyFrom(const C_Move& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_Move::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void C_Move::Swap(C_Move* other) {
  if (other == this) return;
  InternalSwap(other);
}
void C_Move::InternalSwap(C_Move* other) {
  std::swap(direction_, other->direction_);
  std::swap(duration_, other->duration_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata C_Move::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C_Move_descriptor_;
  metadata.reflection = C_Move_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// C_Move

// required uint32 direction = 1;
bool C_Move::has_direction() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void C_Move::set_has_direction() {
  _has_bits_[0] |= 0x00000001u;
}
void C_Move::clear_has_direction() {
  _has_bits_[0] &= ~0x00000001u;
}
void C_Move::clear_direction() {
  direction_ = 0u;
  clear_has_direction();
}
 ::google::protobuf::uint32 C_Move::direction() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Move.direction)
  return direction_;
}
 void C_Move::set_direction(::google::protobuf::uint32 value) {
  set_has_direction();
  direction_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Move.direction)
}

// required uint32 duration = 2;
bool C_Move::has_duration() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void C_Move::set_has_duration() {
  _has_bits_[0] |= 0x00000002u;
}
void C_Move::clear_has_duration() {
  _has_bits_[0] &= ~0x00000002u;
}
void C_Move::clear_duration() {
  duration_ = 0u;
  clear_has_duration();
}
 ::google::protobuf::uint32 C_Move::duration() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Move.duration)
  return duration_;
}
 void C_Move::set_duration(::google::protobuf::uint32 value) {
  set_has_duration();
  duration_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Move.duration)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int S_Move::kUidFieldNumber;
const int S_Move::kXFieldNumber;
const int S_Move::kYFieldNumber;
#endif  // !_MSC_VER

S_Move::S_Move()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:InGamePacket.S_Move)
}

void S_Move::InitAsDefaultInstance() {
}

S_Move::S_Move(const S_Move& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:InGamePacket.S_Move)
}

void S_Move::SharedCtor() {
  _cached_size_ = 0;
  uid_ = 0u;
  x_ = 0u;
  y_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S_Move::~S_Move() {
  // @@protoc_insertion_point(destructor:InGamePacket.S_Move)
  SharedDtor();
}

void S_Move::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S_Move::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S_Move::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S_Move_descriptor_;
}

const S_Move& S_Move::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InGamePacket_2eproto();
  return *default_instance_;
}

S_Move* S_Move::default_instance_ = NULL;

S_Move* S_Move::New(::google::protobuf::Arena* arena) const {
  S_Move* n = new S_Move;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S_Move::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<S_Move*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(uid_, y_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool S_Move::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:InGamePacket.S_Move)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 uid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_x;
        break;
      }

      // required uint32 x = 2;
      case 2: {
        if (tag == 16) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_y;
        break;
      }

      // required uint32 y = 3;
      case 3: {
        if (tag == 24) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:InGamePacket.S_Move)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:InGamePacket.S_Move)
  return false;
#undef DO_
}

void S_Move::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:InGamePacket.S_Move)
  // required uint32 uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uid(), output);
  }

  // required uint32 x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->x(), output);
  }

  // required uint32 y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->y(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:InGamePacket.S_Move)
}

::google::protobuf::uint8* S_Move::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:InGamePacket.S_Move)
  // required uint32 uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uid(), target);
  }

  // required uint32 x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->x(), target);
  }

  // required uint32 y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->y(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InGamePacket.S_Move)
  return target;
}

int S_Move::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_uid()) {
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());
  }

  if (has_x()) {
    // required uint32 x = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->x());
  }

  if (has_y()) {
    // required uint32 y = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->y());
  }

  return total_size;
}
int S_Move::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());

    // required uint32 x = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->x());

    // required uint32 y = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->y());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S_Move::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const S_Move* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const S_Move>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S_Move::MergeFrom(const S_Move& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void S_Move::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S_Move::CopyFrom(const S_Move& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_Move::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void S_Move::Swap(S_Move* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S_Move::InternalSwap(S_Move* other) {
  std::swap(uid_, other->uid_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S_Move::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S_Move_descriptor_;
  metadata.reflection = S_Move_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S_Move

// required uint32 uid = 1;
bool S_Move::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void S_Move::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
void S_Move::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
void S_Move::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
 ::google::protobuf::uint32 S_Move::uid() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Move.uid)
  return uid_;
}
 void S_Move::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Move.uid)
}

// required uint32 x = 2;
bool S_Move::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void S_Move::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
void S_Move::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
void S_Move::clear_x() {
  x_ = 0u;
  clear_has_x();
}
 ::google::protobuf::uint32 S_Move::x() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Move.x)
  return x_;
}
 void S_Move::set_x(::google::protobuf::uint32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Move.x)
}

// required uint32 y = 3;
bool S_Move::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void S_Move::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
void S_Move::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
void S_Move::clear_y() {
  y_ = 0u;
  clear_has_y();
}
 ::google::protobuf::uint32 S_Move::y() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Move.y)
  return y_;
}
 void S_Move::set_y(::google::protobuf::uint32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Move.y)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace InGamePacket

// @@protoc_insertion_point(global_scope)
