// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InGamePacket.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "InGamePacket.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace InGamePacket {

namespace {

const ::google::protobuf::Descriptor* C_Move_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C_Move_reflection_ = NULL;
const ::google::protobuf::Descriptor* S_Move_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S_Move_reflection_ = NULL;
const ::google::protobuf::Descriptor* C_Stop_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C_Stop_reflection_ = NULL;
const ::google::protobuf::Descriptor* S_Stop_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S_Stop_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_InGamePacket_2eproto() {
  protobuf_AddDesc_InGamePacket_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "InGamePacket.proto");
  GOOGLE_CHECK(file != NULL);
  C_Move_descriptor_ = file->message_type(0);
  static const int C_Move_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, velocity_),
  };
  C_Move_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      C_Move_descriptor_,
      C_Move::default_instance_,
      C_Move_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, _has_bits_[0]),
      -1,
      -1,
      sizeof(C_Move),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Move, _internal_metadata_),
      -1);
  S_Move_descriptor_ = file->message_type(1);
  static const int S_Move_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, velocity_),
  };
  S_Move_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      S_Move_descriptor_,
      S_Move::default_instance_,
      S_Move_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, _has_bits_[0]),
      -1,
      -1,
      sizeof(S_Move),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Move, _internal_metadata_),
      -1);
  C_Stop_descriptor_ = file->message_type(2);
  static const int C_Stop_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Stop, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Stop, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Stop, y_),
  };
  C_Stop_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      C_Stop_descriptor_,
      C_Stop::default_instance_,
      C_Stop_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Stop, _has_bits_[0]),
      -1,
      -1,
      sizeof(C_Stop),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C_Stop, _internal_metadata_),
      -1);
  S_Stop_descriptor_ = file->message_type(3);
  static const int S_Stop_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Stop, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Stop, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Stop, y_),
  };
  S_Stop_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      S_Stop_descriptor_,
      S_Stop::default_instance_,
      S_Stop_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Stop, _has_bits_[0]),
      -1,
      -1,
      sizeof(S_Stop),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Stop, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_InGamePacket_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      C_Move_descriptor_, &C_Move::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      S_Move_descriptor_, &S_Move::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      C_Stop_descriptor_, &C_Stop::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      S_Stop_descriptor_, &S_Stop::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_InGamePacket_2eproto() {
  delete C_Move::default_instance_;
  delete C_Move_reflection_;
  delete S_Move::default_instance_;
  delete S_Move_reflection_;
  delete C_Stop::default_instance_;
  delete C_Stop_reflection_;
  delete S_Stop::default_instance_;
  delete S_Stop_reflection_;
}

void protobuf_AddDesc_InGamePacket_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022InGamePacket.proto\022\014InGamePacket\"=\n\006C_"
    "Move\022\013\n\003uid\030\001 \002(\r\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\022"
    "\020\n\010velocity\030\004 \002(\002\"=\n\006S_Move\022\013\n\003uid\030\001 \002(\r"
    "\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030\003 \002(\002\022\020\n\010velocity\030\004 \002(\002"
    "\"+\n\006C_Stop\022\013\n\003uid\030\001 \002(\002\022\t\n\001x\030\002 \002(\002\022\t\n\001y\030"
    "\003 \002(\002\"+\n\006S_Stop\022\013\n\003uid\030\001 \002(\r\022\t\n\001x\030\002 \002(\002\022"
    "\t\n\001y\030\003 \002(\002", 250);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "InGamePacket.proto", &protobuf_RegisterTypes);
  C_Move::default_instance_ = new C_Move();
  S_Move::default_instance_ = new S_Move();
  C_Stop::default_instance_ = new C_Stop();
  S_Stop::default_instance_ = new S_Stop();
  C_Move::default_instance_->InitAsDefaultInstance();
  S_Move::default_instance_->InitAsDefaultInstance();
  C_Stop::default_instance_->InitAsDefaultInstance();
  S_Stop::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_InGamePacket_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_InGamePacket_2eproto {
  StaticDescriptorInitializer_InGamePacket_2eproto() {
    protobuf_AddDesc_InGamePacket_2eproto();
  }
} static_descriptor_initializer_InGamePacket_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int C_Move::kUidFieldNumber;
const int C_Move::kXFieldNumber;
const int C_Move::kYFieldNumber;
const int C_Move::kVelocityFieldNumber;
#endif  // !_MSC_VER

C_Move::C_Move()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:InGamePacket.C_Move)
}

void C_Move::InitAsDefaultInstance() {
}

C_Move::C_Move(const C_Move& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:InGamePacket.C_Move)
}

void C_Move::SharedCtor() {
  _cached_size_ = 0;
  uid_ = 0u;
  x_ = 0;
  y_ = 0;
  velocity_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C_Move::~C_Move() {
  // @@protoc_insertion_point(destructor:InGamePacket.C_Move)
  SharedDtor();
}

void C_Move::SharedDtor() {
  if (this != default_instance_) {
  }
}

void C_Move::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C_Move::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C_Move_descriptor_;
}

const C_Move& C_Move::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InGamePacket_2eproto();
  return *default_instance_;
}

C_Move* C_Move::default_instance_ = NULL;

C_Move* C_Move::New(::google::protobuf::Arena* arena) const {
  C_Move* n = new C_Move;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void C_Move::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<C_Move*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(uid_, velocity_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool C_Move::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:InGamePacket.C_Move)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 uid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_x;
        break;
      }

      // required float x = 2;
      case 2: {
        if (tag == 21) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_y;
        break;
      }

      // required float y = 3;
      case 3: {
        if (tag == 29) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_velocity;
        break;
      }

      // required float velocity = 4;
      case 4: {
        if (tag == 37) {
         parse_velocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &velocity_)));
          set_has_velocity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:InGamePacket.C_Move)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:InGamePacket.C_Move)
  return false;
#undef DO_
}

void C_Move::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:InGamePacket.C_Move)
  // required uint32 uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uid(), output);
  }

  // required float x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }

  // required float y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }

  // required float velocity = 4;
  if (has_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->velocity(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:InGamePacket.C_Move)
}

::google::protobuf::uint8* C_Move::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:InGamePacket.C_Move)
  // required uint32 uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uid(), target);
  }

  // required float x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }

  // required float y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }

  // required float velocity = 4;
  if (has_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->velocity(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InGamePacket.C_Move)
  return target;
}

int C_Move::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_uid()) {
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());
  }

  if (has_x()) {
    // required float x = 2;
    total_size += 1 + 4;
  }

  if (has_y()) {
    // required float y = 3;
    total_size += 1 + 4;
  }

  if (has_velocity()) {
    // required float velocity = 4;
    total_size += 1 + 4;
  }

  return total_size;
}
int C_Move::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());

    // required float x = 2;
    total_size += 1 + 4;

    // required float y = 3;
    total_size += 1 + 4;

    // required float velocity = 4;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C_Move::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const C_Move* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const C_Move>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C_Move::MergeFrom(const C_Move& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_velocity()) {
      set_velocity(from.velocity());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void C_Move::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C_Move::CopyFrom(const C_Move& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_Move::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void C_Move::Swap(C_Move* other) {
  if (other == this) return;
  InternalSwap(other);
}
void C_Move::InternalSwap(C_Move* other) {
  std::swap(uid_, other->uid_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(velocity_, other->velocity_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata C_Move::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C_Move_descriptor_;
  metadata.reflection = C_Move_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// C_Move

// required uint32 uid = 1;
bool C_Move::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void C_Move::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
void C_Move::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
void C_Move::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
 ::google::protobuf::uint32 C_Move::uid() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Move.uid)
  return uid_;
}
 void C_Move::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Move.uid)
}

// required float x = 2;
bool C_Move::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void C_Move::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
void C_Move::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
void C_Move::clear_x() {
  x_ = 0;
  clear_has_x();
}
 float C_Move::x() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Move.x)
  return x_;
}
 void C_Move::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Move.x)
}

// required float y = 3;
bool C_Move::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void C_Move::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
void C_Move::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
void C_Move::clear_y() {
  y_ = 0;
  clear_has_y();
}
 float C_Move::y() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Move.y)
  return y_;
}
 void C_Move::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Move.y)
}

// required float velocity = 4;
bool C_Move::has_velocity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void C_Move::set_has_velocity() {
  _has_bits_[0] |= 0x00000008u;
}
void C_Move::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000008u;
}
void C_Move::clear_velocity() {
  velocity_ = 0;
  clear_has_velocity();
}
 float C_Move::velocity() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Move.velocity)
  return velocity_;
}
 void C_Move::set_velocity(float value) {
  set_has_velocity();
  velocity_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Move.velocity)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int S_Move::kUidFieldNumber;
const int S_Move::kXFieldNumber;
const int S_Move::kYFieldNumber;
const int S_Move::kVelocityFieldNumber;
#endif  // !_MSC_VER

S_Move::S_Move()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:InGamePacket.S_Move)
}

void S_Move::InitAsDefaultInstance() {
}

S_Move::S_Move(const S_Move& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:InGamePacket.S_Move)
}

void S_Move::SharedCtor() {
  _cached_size_ = 0;
  uid_ = 0u;
  x_ = 0;
  y_ = 0;
  velocity_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S_Move::~S_Move() {
  // @@protoc_insertion_point(destructor:InGamePacket.S_Move)
  SharedDtor();
}

void S_Move::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S_Move::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S_Move::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S_Move_descriptor_;
}

const S_Move& S_Move::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InGamePacket_2eproto();
  return *default_instance_;
}

S_Move* S_Move::default_instance_ = NULL;

S_Move* S_Move::New(::google::protobuf::Arena* arena) const {
  S_Move* n = new S_Move;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S_Move::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<S_Move*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(uid_, velocity_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool S_Move::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:InGamePacket.S_Move)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 uid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_x;
        break;
      }

      // required float x = 2;
      case 2: {
        if (tag == 21) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_y;
        break;
      }

      // required float y = 3;
      case 3: {
        if (tag == 29) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_velocity;
        break;
      }

      // required float velocity = 4;
      case 4: {
        if (tag == 37) {
         parse_velocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &velocity_)));
          set_has_velocity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:InGamePacket.S_Move)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:InGamePacket.S_Move)
  return false;
#undef DO_
}

void S_Move::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:InGamePacket.S_Move)
  // required uint32 uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uid(), output);
  }

  // required float x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }

  // required float y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }

  // required float velocity = 4;
  if (has_velocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->velocity(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:InGamePacket.S_Move)
}

::google::protobuf::uint8* S_Move::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:InGamePacket.S_Move)
  // required uint32 uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uid(), target);
  }

  // required float x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }

  // required float y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }

  // required float velocity = 4;
  if (has_velocity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->velocity(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InGamePacket.S_Move)
  return target;
}

int S_Move::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_uid()) {
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());
  }

  if (has_x()) {
    // required float x = 2;
    total_size += 1 + 4;
  }

  if (has_y()) {
    // required float y = 3;
    total_size += 1 + 4;
  }

  if (has_velocity()) {
    // required float velocity = 4;
    total_size += 1 + 4;
  }

  return total_size;
}
int S_Move::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());

    // required float x = 2;
    total_size += 1 + 4;

    // required float y = 3;
    total_size += 1 + 4;

    // required float velocity = 4;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S_Move::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const S_Move* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const S_Move>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S_Move::MergeFrom(const S_Move& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_velocity()) {
      set_velocity(from.velocity());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void S_Move::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S_Move::CopyFrom(const S_Move& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_Move::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void S_Move::Swap(S_Move* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S_Move::InternalSwap(S_Move* other) {
  std::swap(uid_, other->uid_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(velocity_, other->velocity_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S_Move::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S_Move_descriptor_;
  metadata.reflection = S_Move_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S_Move

// required uint32 uid = 1;
bool S_Move::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void S_Move::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
void S_Move::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
void S_Move::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
 ::google::protobuf::uint32 S_Move::uid() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Move.uid)
  return uid_;
}
 void S_Move::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Move.uid)
}

// required float x = 2;
bool S_Move::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void S_Move::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
void S_Move::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
void S_Move::clear_x() {
  x_ = 0;
  clear_has_x();
}
 float S_Move::x() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Move.x)
  return x_;
}
 void S_Move::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Move.x)
}

// required float y = 3;
bool S_Move::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void S_Move::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
void S_Move::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
void S_Move::clear_y() {
  y_ = 0;
  clear_has_y();
}
 float S_Move::y() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Move.y)
  return y_;
}
 void S_Move::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Move.y)
}

// required float velocity = 4;
bool S_Move::has_velocity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void S_Move::set_has_velocity() {
  _has_bits_[0] |= 0x00000008u;
}
void S_Move::clear_has_velocity() {
  _has_bits_[0] &= ~0x00000008u;
}
void S_Move::clear_velocity() {
  velocity_ = 0;
  clear_has_velocity();
}
 float S_Move::velocity() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Move.velocity)
  return velocity_;
}
 void S_Move::set_velocity(float value) {
  set_has_velocity();
  velocity_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Move.velocity)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int C_Stop::kUidFieldNumber;
const int C_Stop::kXFieldNumber;
const int C_Stop::kYFieldNumber;
#endif  // !_MSC_VER

C_Stop::C_Stop()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:InGamePacket.C_Stop)
}

void C_Stop::InitAsDefaultInstance() {
}

C_Stop::C_Stop(const C_Stop& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:InGamePacket.C_Stop)
}

void C_Stop::SharedCtor() {
  _cached_size_ = 0;
  uid_ = 0;
  x_ = 0;
  y_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C_Stop::~C_Stop() {
  // @@protoc_insertion_point(destructor:InGamePacket.C_Stop)
  SharedDtor();
}

void C_Stop::SharedDtor() {
  if (this != default_instance_) {
  }
}

void C_Stop::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C_Stop::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C_Stop_descriptor_;
}

const C_Stop& C_Stop::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InGamePacket_2eproto();
  return *default_instance_;
}

C_Stop* C_Stop::default_instance_ = NULL;

C_Stop* C_Stop::New(::google::protobuf::Arena* arena) const {
  C_Stop* n = new C_Stop;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void C_Stop::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<C_Stop*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(uid_, y_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool C_Stop::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:InGamePacket.C_Stop)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float uid = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_x;
        break;
      }

      // required float x = 2;
      case 2: {
        if (tag == 21) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_y;
        break;
      }

      // required float y = 3;
      case 3: {
        if (tag == 29) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:InGamePacket.C_Stop)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:InGamePacket.C_Stop)
  return false;
#undef DO_
}

void C_Stop::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:InGamePacket.C_Stop)
  // required float uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->uid(), output);
  }

  // required float x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }

  // required float y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:InGamePacket.C_Stop)
}

::google::protobuf::uint8* C_Stop::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:InGamePacket.C_Stop)
  // required float uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->uid(), target);
  }

  // required float x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }

  // required float y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InGamePacket.C_Stop)
  return target;
}

int C_Stop::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_uid()) {
    // required float uid = 1;
    total_size += 1 + 4;
  }

  if (has_x()) {
    // required float x = 2;
    total_size += 1 + 4;
  }

  if (has_y()) {
    // required float y = 3;
    total_size += 1 + 4;
  }

  return total_size;
}
int C_Stop::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required float uid = 1;
    total_size += 1 + 4;

    // required float x = 2;
    total_size += 1 + 4;

    // required float y = 3;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C_Stop::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const C_Stop* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const C_Stop>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C_Stop::MergeFrom(const C_Stop& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void C_Stop::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C_Stop::CopyFrom(const C_Stop& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_Stop::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void C_Stop::Swap(C_Stop* other) {
  if (other == this) return;
  InternalSwap(other);
}
void C_Stop::InternalSwap(C_Stop* other) {
  std::swap(uid_, other->uid_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata C_Stop::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C_Stop_descriptor_;
  metadata.reflection = C_Stop_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// C_Stop

// required float uid = 1;
bool C_Stop::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void C_Stop::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
void C_Stop::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
void C_Stop::clear_uid() {
  uid_ = 0;
  clear_has_uid();
}
 float C_Stop::uid() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Stop.uid)
  return uid_;
}
 void C_Stop::set_uid(float value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Stop.uid)
}

// required float x = 2;
bool C_Stop::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void C_Stop::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
void C_Stop::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
void C_Stop::clear_x() {
  x_ = 0;
  clear_has_x();
}
 float C_Stop::x() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Stop.x)
  return x_;
}
 void C_Stop::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Stop.x)
}

// required float y = 3;
bool C_Stop::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void C_Stop::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
void C_Stop::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
void C_Stop::clear_y() {
  y_ = 0;
  clear_has_y();
}
 float C_Stop::y() const {
  // @@protoc_insertion_point(field_get:InGamePacket.C_Stop.y)
  return y_;
}
 void C_Stop::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.C_Stop.y)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int S_Stop::kUidFieldNumber;
const int S_Stop::kXFieldNumber;
const int S_Stop::kYFieldNumber;
#endif  // !_MSC_VER

S_Stop::S_Stop()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:InGamePacket.S_Stop)
}

void S_Stop::InitAsDefaultInstance() {
}

S_Stop::S_Stop(const S_Stop& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:InGamePacket.S_Stop)
}

void S_Stop::SharedCtor() {
  _cached_size_ = 0;
  uid_ = 0u;
  x_ = 0;
  y_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S_Stop::~S_Stop() {
  // @@protoc_insertion_point(destructor:InGamePacket.S_Stop)
  SharedDtor();
}

void S_Stop::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S_Stop::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S_Stop::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S_Stop_descriptor_;
}

const S_Stop& S_Stop::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_InGamePacket_2eproto();
  return *default_instance_;
}

S_Stop* S_Stop::default_instance_ = NULL;

S_Stop* S_Stop::New(::google::protobuf::Arena* arena) const {
  S_Stop* n = new S_Stop;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S_Stop::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<S_Stop*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(uid_, y_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool S_Stop::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:InGamePacket.S_Stop)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 uid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_x;
        break;
      }

      // required float x = 2;
      case 2: {
        if (tag == 21) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_y;
        break;
      }

      // required float y = 3;
      case 3: {
        if (tag == 29) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:InGamePacket.S_Stop)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:InGamePacket.S_Stop)
  return false;
#undef DO_
}

void S_Stop::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:InGamePacket.S_Stop)
  // required uint32 uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uid(), output);
  }

  // required float x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }

  // required float y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:InGamePacket.S_Stop)
}

::google::protobuf::uint8* S_Stop::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:InGamePacket.S_Stop)
  // required uint32 uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uid(), target);
  }

  // required float x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }

  // required float y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InGamePacket.S_Stop)
  return target;
}

int S_Stop::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_uid()) {
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());
  }

  if (has_x()) {
    // required float x = 2;
    total_size += 1 + 4;
  }

  if (has_y()) {
    // required float y = 3;
    total_size += 1 + 4;
  }

  return total_size;
}
int S_Stop::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());

    // required float x = 2;
    total_size += 1 + 4;

    // required float y = 3;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S_Stop::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const S_Stop* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const S_Stop>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S_Stop::MergeFrom(const S_Stop& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void S_Stop::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S_Stop::CopyFrom(const S_Stop& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_Stop::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void S_Stop::Swap(S_Stop* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S_Stop::InternalSwap(S_Stop* other) {
  std::swap(uid_, other->uid_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S_Stop::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S_Stop_descriptor_;
  metadata.reflection = S_Stop_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S_Stop

// required uint32 uid = 1;
bool S_Stop::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void S_Stop::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
void S_Stop::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
void S_Stop::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
 ::google::protobuf::uint32 S_Stop::uid() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Stop.uid)
  return uid_;
}
 void S_Stop::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Stop.uid)
}

// required float x = 2;
bool S_Stop::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void S_Stop::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
void S_Stop::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
void S_Stop::clear_x() {
  x_ = 0;
  clear_has_x();
}
 float S_Stop::x() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Stop.x)
  return x_;
}
 void S_Stop::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Stop.x)
}

// required float y = 3;
bool S_Stop::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void S_Stop::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
void S_Stop::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
void S_Stop::clear_y() {
  y_ = 0;
  clear_has_y();
}
 float S_Stop::y() const {
  // @@protoc_insertion_point(field_get:InGamePacket.S_Stop.y)
  return y_;
}
 void S_Stop::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:InGamePacket.S_Stop.y)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace InGamePacket

// @@protoc_insertion_point(global_scope)
