// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountPacket.proto

#ifndef PROTOBUF_AccountPacket_2eproto__INCLUDED
#define PROTOBUF_AccountPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace AccountPacket {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_AccountPacket_2eproto();
void protobuf_AssignDesc_AccountPacket_2eproto();
void protobuf_ShutdownFile_AccountPacket_2eproto();

class S_Account_List;
class S_Account_List_Disconnect;
class S_Account_List_Account;

// ===================================================================

class S_Account_List_Disconnect : public ::google::protobuf::Message {
 public:
  S_Account_List_Disconnect();
  virtual ~S_Account_List_Disconnect();

  S_Account_List_Disconnect(const S_Account_List_Disconnect& from);

  inline S_Account_List_Disconnect& operator=(const S_Account_List_Disconnect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S_Account_List_Disconnect& default_instance();

  void Swap(S_Account_List_Disconnect* other);

  // implements Message ----------------------------------------------

  inline S_Account_List_Disconnect* New() const { return New(NULL); }

  S_Account_List_Disconnect* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S_Account_List_Disconnect& from);
  void MergeFrom(const S_Account_List_Disconnect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S_Account_List_Disconnect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uid = 1;
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint32 uid() const;
  void set_uid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:AccountPacket.S_Account_List.Disconnect)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 uid_;
  friend void  protobuf_AddDesc_AccountPacket_2eproto();
  friend void protobuf_AssignDesc_AccountPacket_2eproto();
  friend void protobuf_ShutdownFile_AccountPacket_2eproto();

  void InitAsDefaultInstance();
  static S_Account_List_Disconnect* default_instance_;
};
// -------------------------------------------------------------------

class S_Account_List_Account : public ::google::protobuf::Message {
 public:
  S_Account_List_Account();
  virtual ~S_Account_List_Account();

  S_Account_List_Account(const S_Account_List_Account& from);

  inline S_Account_List_Account& operator=(const S_Account_List_Account& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S_Account_List_Account& default_instance();

  void Swap(S_Account_List_Account* other);

  // implements Message ----------------------------------------------

  inline S_Account_List_Account* New() const { return New(NULL); }

  S_Account_List_Account* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S_Account_List_Account& from);
  void MergeFrom(const S_Account_List_Account& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S_Account_List_Account* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uid = 1;
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint32 uid() const;
  void set_uid(::google::protobuf::uint32 value);

  // required uint32 hp = 2;
  bool has_hp() const;
  void clear_hp();
  static const int kHpFieldNumber = 2;
  ::google::protobuf::uint32 hp() const;
  void set_hp(::google::protobuf::uint32 value);

  // required float x = 3;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 3;
  float x() const;
  void set_x(float value);

  // required float y = 4;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 4;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:AccountPacket.S_Account_List.Account)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 hp_;
  float x_;
  float y_;
  friend void  protobuf_AddDesc_AccountPacket_2eproto();
  friend void protobuf_AssignDesc_AccountPacket_2eproto();
  friend void protobuf_ShutdownFile_AccountPacket_2eproto();

  void InitAsDefaultInstance();
  static S_Account_List_Account* default_instance_;
};
// -------------------------------------------------------------------

class S_Account_List : public ::google::protobuf::Message {
 public:
  S_Account_List();
  virtual ~S_Account_List();

  S_Account_List(const S_Account_List& from);

  inline S_Account_List& operator=(const S_Account_List& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S_Account_List& default_instance();

  void Swap(S_Account_List* other);

  // implements Message ----------------------------------------------

  inline S_Account_List* New() const { return New(NULL); }

  S_Account_List* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S_Account_List& from);
  void MergeFrom(const S_Account_List& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S_Account_List* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef S_Account_List_Disconnect Disconnect;
  typedef S_Account_List_Account Account;

  // accessors -------------------------------------------------------

  // repeated .AccountPacket.S_Account_List.Account Account_Member = 1;
  int account_member_size() const;
  void clear_account_member();
  static const int kAccountMemberFieldNumber = 1;
  const ::AccountPacket::S_Account_List_Account& account_member(int index) const;
  ::AccountPacket::S_Account_List_Account* mutable_account_member(int index);
  ::AccountPacket::S_Account_List_Account* add_account_member();
  const ::google::protobuf::RepeatedPtrField< ::AccountPacket::S_Account_List_Account >&
      account_member() const;
  ::google::protobuf::RepeatedPtrField< ::AccountPacket::S_Account_List_Account >*
      mutable_account_member();

  // @@protoc_insertion_point(class_scope:AccountPacket.S_Account_List)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::AccountPacket::S_Account_List_Account > account_member_;
  friend void  protobuf_AddDesc_AccountPacket_2eproto();
  friend void protobuf_AssignDesc_AccountPacket_2eproto();
  friend void protobuf_ShutdownFile_AccountPacket_2eproto();

  void InitAsDefaultInstance();
  static S_Account_List* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// S_Account_List_Disconnect

// required uint32 uid = 1;
inline bool S_Account_List_Disconnect::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S_Account_List_Disconnect::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S_Account_List_Disconnect::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S_Account_List_Disconnect::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
inline ::google::protobuf::uint32 S_Account_List_Disconnect::uid() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Disconnect.uid)
  return uid_;
}
inline void S_Account_List_Disconnect::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Disconnect.uid)
}

// -------------------------------------------------------------------

// S_Account_List_Account

// required uint32 uid = 1;
inline bool S_Account_List_Account::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S_Account_List_Account::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S_Account_List_Account::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S_Account_List_Account::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
inline ::google::protobuf::uint32 S_Account_List_Account::uid() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.uid)
  return uid_;
}
inline void S_Account_List_Account::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.uid)
}

// required uint32 hp = 2;
inline bool S_Account_List_Account::has_hp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S_Account_List_Account::set_has_hp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S_Account_List_Account::clear_has_hp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S_Account_List_Account::clear_hp() {
  hp_ = 0u;
  clear_has_hp();
}
inline ::google::protobuf::uint32 S_Account_List_Account::hp() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.hp)
  return hp_;
}
inline void S_Account_List_Account::set_hp(::google::protobuf::uint32 value) {
  set_has_hp();
  hp_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.hp)
}

// required float x = 3;
inline bool S_Account_List_Account::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S_Account_List_Account::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S_Account_List_Account::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S_Account_List_Account::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float S_Account_List_Account::x() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.x)
  return x_;
}
inline void S_Account_List_Account::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.x)
}

// required float y = 4;
inline bool S_Account_List_Account::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void S_Account_List_Account::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void S_Account_List_Account::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void S_Account_List_Account::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float S_Account_List_Account::y() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.y)
  return y_;
}
inline void S_Account_List_Account::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.y)
}

// -------------------------------------------------------------------

// S_Account_List

// repeated .AccountPacket.S_Account_List.Account Account_Member = 1;
inline int S_Account_List::account_member_size() const {
  return account_member_.size();
}
inline void S_Account_List::clear_account_member() {
  account_member_.Clear();
}
inline const ::AccountPacket::S_Account_List_Account& S_Account_List::account_member(int index) const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account_Member)
  return account_member_.Get(index);
}
inline ::AccountPacket::S_Account_List_Account* S_Account_List::mutable_account_member(int index) {
  // @@protoc_insertion_point(field_mutable:AccountPacket.S_Account_List.Account_Member)
  return account_member_.Mutable(index);
}
inline ::AccountPacket::S_Account_List_Account* S_Account_List::add_account_member() {
  // @@protoc_insertion_point(field_add:AccountPacket.S_Account_List.Account_Member)
  return account_member_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::AccountPacket::S_Account_List_Account >&
S_Account_List::account_member() const {
  // @@protoc_insertion_point(field_list:AccountPacket.S_Account_List.Account_Member)
  return account_member_;
}
inline ::google::protobuf::RepeatedPtrField< ::AccountPacket::S_Account_List_Account >*
S_Account_List::mutable_account_member() {
  // @@protoc_insertion_point(field_mutable_list:AccountPacket.S_Account_List.Account_Member)
  return &account_member_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace AccountPacket

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AccountPacket_2eproto__INCLUDED
