// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountPacket.proto

#ifndef PROTOBUF_AccountPacket_2eproto__INCLUDED
#define PROTOBUF_AccountPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace AccountPacket {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_AccountPacket_2eproto();
void protobuf_AssignDesc_AccountPacket_2eproto();
void protobuf_ShutdownFile_AccountPacket_2eproto();

class S_Account;

// ===================================================================

class S_Account : public ::google::protobuf::Message {
 public:
  S_Account();
  virtual ~S_Account();

  S_Account(const S_Account& from);

  inline S_Account& operator=(const S_Account& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S_Account& default_instance();

  void Swap(S_Account* other);

  // implements Message ----------------------------------------------

  inline S_Account* New() const { return New(NULL); }

  S_Account* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S_Account& from);
  void MergeFrom(const S_Account& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S_Account* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uid = 1;
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::uint32 uid() const;
  void set_uid(::google::protobuf::uint32 value);

  // required uint32 hp = 2;
  bool has_hp() const;
  void clear_hp();
  static const int kHpFieldNumber = 2;
  ::google::protobuf::uint32 hp() const;
  void set_hp(::google::protobuf::uint32 value);

  // required uint32 x = 3;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 3;
  ::google::protobuf::uint32 x() const;
  void set_x(::google::protobuf::uint32 value);

  // required uint32 y = 4;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 4;
  ::google::protobuf::uint32 y() const;
  void set_y(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:AccountPacket.S_Account)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 hp_;
  ::google::protobuf::uint32 x_;
  ::google::protobuf::uint32 y_;
  friend void  protobuf_AddDesc_AccountPacket_2eproto();
  friend void protobuf_AssignDesc_AccountPacket_2eproto();
  friend void protobuf_ShutdownFile_AccountPacket_2eproto();

  void InitAsDefaultInstance();
  static S_Account* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// S_Account

// required uint32 uid = 1;
inline bool S_Account::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S_Account::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S_Account::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S_Account::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
inline ::google::protobuf::uint32 S_Account::uid() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account.uid)
  return uid_;
}
inline void S_Account::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account.uid)
}

// required uint32 hp = 2;
inline bool S_Account::has_hp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S_Account::set_has_hp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S_Account::clear_has_hp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S_Account::clear_hp() {
  hp_ = 0u;
  clear_has_hp();
}
inline ::google::protobuf::uint32 S_Account::hp() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account.hp)
  return hp_;
}
inline void S_Account::set_hp(::google::protobuf::uint32 value) {
  set_has_hp();
  hp_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account.hp)
}

// required uint32 x = 3;
inline bool S_Account::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S_Account::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S_Account::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S_Account::clear_x() {
  x_ = 0u;
  clear_has_x();
}
inline ::google::protobuf::uint32 S_Account::x() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account.x)
  return x_;
}
inline void S_Account::set_x(::google::protobuf::uint32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account.x)
}

// required uint32 y = 4;
inline bool S_Account::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void S_Account::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void S_Account::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void S_Account::clear_y() {
  y_ = 0u;
  clear_has_y();
}
inline ::google::protobuf::uint32 S_Account::y() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account.y)
  return y_;
}
inline void S_Account::set_y(::google::protobuf::uint32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account.y)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace AccountPacket

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AccountPacket_2eproto__INCLUDED
