// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountPacket.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AccountPacket.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace AccountPacket {

namespace {

const ::google::protobuf::Descriptor* S_Account_List_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S_Account_List_reflection_ = NULL;
const ::google::protobuf::Descriptor* S_Account_List_Disconnect_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S_Account_List_Disconnect_reflection_ = NULL;
const ::google::protobuf::Descriptor* S_Account_List_Account_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S_Account_List_Account_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_AccountPacket_2eproto() {
  protobuf_AddDesc_AccountPacket_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "AccountPacket.proto");
  GOOGLE_CHECK(file != NULL);
  S_Account_List_descriptor_ = file->message_type(0);
  static const int S_Account_List_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List, account_member_),
  };
  S_Account_List_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      S_Account_List_descriptor_,
      S_Account_List::default_instance_,
      S_Account_List_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List, _has_bits_[0]),
      -1,
      -1,
      sizeof(S_Account_List),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List, _internal_metadata_),
      -1);
  S_Account_List_Disconnect_descriptor_ = S_Account_List_descriptor_->nested_type(0);
  static const int S_Account_List_Disconnect_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Disconnect, uid_),
  };
  S_Account_List_Disconnect_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      S_Account_List_Disconnect_descriptor_,
      S_Account_List_Disconnect::default_instance_,
      S_Account_List_Disconnect_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Disconnect, _has_bits_[0]),
      -1,
      -1,
      sizeof(S_Account_List_Disconnect),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Disconnect, _internal_metadata_),
      -1);
  S_Account_List_Account_descriptor_ = S_Account_List_descriptor_->nested_type(1);
  static const int S_Account_List_Account_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Account, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Account, hp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Account, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Account, y_),
  };
  S_Account_List_Account_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      S_Account_List_Account_descriptor_,
      S_Account_List_Account::default_instance_,
      S_Account_List_Account_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Account, _has_bits_[0]),
      -1,
      -1,
      sizeof(S_Account_List_Account),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S_Account_List_Account, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_AccountPacket_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      S_Account_List_descriptor_, &S_Account_List::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      S_Account_List_Disconnect_descriptor_, &S_Account_List_Disconnect::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      S_Account_List_Account_descriptor_, &S_Account_List_Account::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_AccountPacket_2eproto() {
  delete S_Account_List::default_instance_;
  delete S_Account_List_reflection_;
  delete S_Account_List_Disconnect::default_instance_;
  delete S_Account_List_Disconnect_reflection_;
  delete S_Account_List_Account::default_instance_;
  delete S_Account_List_Account_reflection_;
}

void protobuf_AddDesc_AccountPacket_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023AccountPacket.proto\022\rAccountPacket\"\244\001\n"
    "\016S_Account_List\022=\n\016Account_Member\030\001 \003(\0132"
    "%.AccountPacket.S_Account_List.Account\032\031"
    "\n\nDisconnect\022\013\n\003uid\030\001 \002(\r\0328\n\007Account\022\013\n\003"
    "uid\030\001 \002(\r\022\n\n\002hp\030\002 \002(\r\022\t\n\001x\030\003 \002(\002\022\t\n\001y\030\004 "
    "\002(\002", 203);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AccountPacket.proto", &protobuf_RegisterTypes);
  S_Account_List::default_instance_ = new S_Account_List();
  S_Account_List_Disconnect::default_instance_ = new S_Account_List_Disconnect();
  S_Account_List_Account::default_instance_ = new S_Account_List_Account();
  S_Account_List::default_instance_->InitAsDefaultInstance();
  S_Account_List_Disconnect::default_instance_->InitAsDefaultInstance();
  S_Account_List_Account::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_AccountPacket_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_AccountPacket_2eproto {
  StaticDescriptorInitializer_AccountPacket_2eproto() {
    protobuf_AddDesc_AccountPacket_2eproto();
  }
} static_descriptor_initializer_AccountPacket_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int S_Account_List_Disconnect::kUidFieldNumber;
#endif  // !_MSC_VER

S_Account_List_Disconnect::S_Account_List_Disconnect()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:AccountPacket.S_Account_List.Disconnect)
}

void S_Account_List_Disconnect::InitAsDefaultInstance() {
}

S_Account_List_Disconnect::S_Account_List_Disconnect(const S_Account_List_Disconnect& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:AccountPacket.S_Account_List.Disconnect)
}

void S_Account_List_Disconnect::SharedCtor() {
  _cached_size_ = 0;
  uid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S_Account_List_Disconnect::~S_Account_List_Disconnect() {
  // @@protoc_insertion_point(destructor:AccountPacket.S_Account_List.Disconnect)
  SharedDtor();
}

void S_Account_List_Disconnect::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S_Account_List_Disconnect::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S_Account_List_Disconnect::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S_Account_List_Disconnect_descriptor_;
}

const S_Account_List_Disconnect& S_Account_List_Disconnect::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AccountPacket_2eproto();
  return *default_instance_;
}

S_Account_List_Disconnect* S_Account_List_Disconnect::default_instance_ = NULL;

S_Account_List_Disconnect* S_Account_List_Disconnect::New(::google::protobuf::Arena* arena) const {
  S_Account_List_Disconnect* n = new S_Account_List_Disconnect;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S_Account_List_Disconnect::Clear() {
  uid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool S_Account_List_Disconnect::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AccountPacket.S_Account_List.Disconnect)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 uid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AccountPacket.S_Account_List.Disconnect)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AccountPacket.S_Account_List.Disconnect)
  return false;
#undef DO_
}

void S_Account_List_Disconnect::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AccountPacket.S_Account_List.Disconnect)
  // required uint32 uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:AccountPacket.S_Account_List.Disconnect)
}

::google::protobuf::uint8* S_Account_List_Disconnect::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:AccountPacket.S_Account_List.Disconnect)
  // required uint32 uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AccountPacket.S_Account_List.Disconnect)
  return target;
}

int S_Account_List_Disconnect::ByteSize() const {
  int total_size = 0;

  // required uint32 uid = 1;
  if (has_uid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S_Account_List_Disconnect::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const S_Account_List_Disconnect* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const S_Account_List_Disconnect>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S_Account_List_Disconnect::MergeFrom(const S_Account_List_Disconnect& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void S_Account_List_Disconnect::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S_Account_List_Disconnect::CopyFrom(const S_Account_List_Disconnect& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_Account_List_Disconnect::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S_Account_List_Disconnect::Swap(S_Account_List_Disconnect* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S_Account_List_Disconnect::InternalSwap(S_Account_List_Disconnect* other) {
  std::swap(uid_, other->uid_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S_Account_List_Disconnect::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S_Account_List_Disconnect_descriptor_;
  metadata.reflection = S_Account_List_Disconnect_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int S_Account_List_Account::kUidFieldNumber;
const int S_Account_List_Account::kHpFieldNumber;
const int S_Account_List_Account::kXFieldNumber;
const int S_Account_List_Account::kYFieldNumber;
#endif  // !_MSC_VER

S_Account_List_Account::S_Account_List_Account()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:AccountPacket.S_Account_List.Account)
}

void S_Account_List_Account::InitAsDefaultInstance() {
}

S_Account_List_Account::S_Account_List_Account(const S_Account_List_Account& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:AccountPacket.S_Account_List.Account)
}

void S_Account_List_Account::SharedCtor() {
  _cached_size_ = 0;
  uid_ = 0u;
  hp_ = 0u;
  x_ = 0;
  y_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S_Account_List_Account::~S_Account_List_Account() {
  // @@protoc_insertion_point(destructor:AccountPacket.S_Account_List.Account)
  SharedDtor();
}

void S_Account_List_Account::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S_Account_List_Account::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S_Account_List_Account::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S_Account_List_Account_descriptor_;
}

const S_Account_List_Account& S_Account_List_Account::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AccountPacket_2eproto();
  return *default_instance_;
}

S_Account_List_Account* S_Account_List_Account::default_instance_ = NULL;

S_Account_List_Account* S_Account_List_Account::New(::google::protobuf::Arena* arena) const {
  S_Account_List_Account* n = new S_Account_List_Account;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S_Account_List_Account::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<S_Account_List_Account*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(uid_, y_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool S_Account_List_Account::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AccountPacket.S_Account_List.Account)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 uid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_hp;
        break;
      }

      // required uint32 hp = 2;
      case 2: {
        if (tag == 16) {
         parse_hp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &hp_)));
          set_has_hp();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_x;
        break;
      }

      // required float x = 3;
      case 3: {
        if (tag == 29) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_y;
        break;
      }

      // required float y = 4;
      case 4: {
        if (tag == 37) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AccountPacket.S_Account_List.Account)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AccountPacket.S_Account_List.Account)
  return false;
#undef DO_
}

void S_Account_List_Account::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AccountPacket.S_Account_List.Account)
  // required uint32 uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uid(), output);
  }

  // required uint32 hp = 2;
  if (has_hp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->hp(), output);
  }

  // required float x = 3;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->x(), output);
  }

  // required float y = 4;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->y(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:AccountPacket.S_Account_List.Account)
}

::google::protobuf::uint8* S_Account_List_Account::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:AccountPacket.S_Account_List.Account)
  // required uint32 uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uid(), target);
  }

  // required uint32 hp = 2;
  if (has_hp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->hp(), target);
  }

  // required float x = 3;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->x(), target);
  }

  // required float y = 4;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->y(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AccountPacket.S_Account_List.Account)
  return target;
}

int S_Account_List_Account::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_uid()) {
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());
  }

  if (has_hp()) {
    // required uint32 hp = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->hp());
  }

  if (has_x()) {
    // required float x = 3;
    total_size += 1 + 4;
  }

  if (has_y()) {
    // required float y = 4;
    total_size += 1 + 4;
  }

  return total_size;
}
int S_Account_List_Account::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required uint32 uid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());

    // required uint32 hp = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->hp());

    // required float x = 3;
    total_size += 1 + 4;

    // required float y = 4;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S_Account_List_Account::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const S_Account_List_Account* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const S_Account_List_Account>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S_Account_List_Account::MergeFrom(const S_Account_List_Account& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_hp()) {
      set_hp(from.hp());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void S_Account_List_Account::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S_Account_List_Account::CopyFrom(const S_Account_List_Account& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_Account_List_Account::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void S_Account_List_Account::Swap(S_Account_List_Account* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S_Account_List_Account::InternalSwap(S_Account_List_Account* other) {
  std::swap(uid_, other->uid_);
  std::swap(hp_, other->hp_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S_Account_List_Account::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S_Account_List_Account_descriptor_;
  metadata.reflection = S_Account_List_Account_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int S_Account_List::kAccountMemberFieldNumber;
#endif  // !_MSC_VER

S_Account_List::S_Account_List()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:AccountPacket.S_Account_List)
}

void S_Account_List::InitAsDefaultInstance() {
}

S_Account_List::S_Account_List(const S_Account_List& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:AccountPacket.S_Account_List)
}

void S_Account_List::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S_Account_List::~S_Account_List() {
  // @@protoc_insertion_point(destructor:AccountPacket.S_Account_List)
  SharedDtor();
}

void S_Account_List::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S_Account_List::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S_Account_List::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S_Account_List_descriptor_;
}

const S_Account_List& S_Account_List::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AccountPacket_2eproto();
  return *default_instance_;
}

S_Account_List* S_Account_List::default_instance_ = NULL;

S_Account_List* S_Account_List::New(::google::protobuf::Arena* arena) const {
  S_Account_List* n = new S_Account_List;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S_Account_List::Clear() {
  account_member_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool S_Account_List::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AccountPacket.S_Account_List)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .AccountPacket.S_Account_List.Account Account_Member = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_Account_Member:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_account_member()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_Account_Member;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AccountPacket.S_Account_List)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AccountPacket.S_Account_List)
  return false;
#undef DO_
}

void S_Account_List::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AccountPacket.S_Account_List)
  // repeated .AccountPacket.S_Account_List.Account Account_Member = 1;
  for (unsigned int i = 0, n = this->account_member_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->account_member(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:AccountPacket.S_Account_List)
}

::google::protobuf::uint8* S_Account_List::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:AccountPacket.S_Account_List)
  // repeated .AccountPacket.S_Account_List.Account Account_Member = 1;
  for (unsigned int i = 0, n = this->account_member_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->account_member(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AccountPacket.S_Account_List)
  return target;
}

int S_Account_List::ByteSize() const {
  int total_size = 0;

  // repeated .AccountPacket.S_Account_List.Account Account_Member = 1;
  total_size += 1 * this->account_member_size();
  for (int i = 0; i < this->account_member_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->account_member(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S_Account_List::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const S_Account_List* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const S_Account_List>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S_Account_List::MergeFrom(const S_Account_List& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  account_member_.MergeFrom(from.account_member_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void S_Account_List::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S_Account_List::CopyFrom(const S_Account_List& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_Account_List::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->account_member())) return false;
  return true;
}

void S_Account_List::Swap(S_Account_List* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S_Account_List::InternalSwap(S_Account_List* other) {
  account_member_.UnsafeArenaSwap(&other->account_member_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S_Account_List::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S_Account_List_descriptor_;
  metadata.reflection = S_Account_List_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S_Account_List_Disconnect

// required uint32 uid = 1;
bool S_Account_List_Disconnect::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void S_Account_List_Disconnect::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
void S_Account_List_Disconnect::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
void S_Account_List_Disconnect::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
 ::google::protobuf::uint32 S_Account_List_Disconnect::uid() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Disconnect.uid)
  return uid_;
}
 void S_Account_List_Disconnect::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Disconnect.uid)
}

// -------------------------------------------------------------------

// S_Account_List_Account

// required uint32 uid = 1;
bool S_Account_List_Account::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void S_Account_List_Account::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
void S_Account_List_Account::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
void S_Account_List_Account::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
 ::google::protobuf::uint32 S_Account_List_Account::uid() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.uid)
  return uid_;
}
 void S_Account_List_Account::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.uid)
}

// required uint32 hp = 2;
bool S_Account_List_Account::has_hp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void S_Account_List_Account::set_has_hp() {
  _has_bits_[0] |= 0x00000002u;
}
void S_Account_List_Account::clear_has_hp() {
  _has_bits_[0] &= ~0x00000002u;
}
void S_Account_List_Account::clear_hp() {
  hp_ = 0u;
  clear_has_hp();
}
 ::google::protobuf::uint32 S_Account_List_Account::hp() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.hp)
  return hp_;
}
 void S_Account_List_Account::set_hp(::google::protobuf::uint32 value) {
  set_has_hp();
  hp_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.hp)
}

// required float x = 3;
bool S_Account_List_Account::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void S_Account_List_Account::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
void S_Account_List_Account::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
void S_Account_List_Account::clear_x() {
  x_ = 0;
  clear_has_x();
}
 float S_Account_List_Account::x() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.x)
  return x_;
}
 void S_Account_List_Account::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.x)
}

// required float y = 4;
bool S_Account_List_Account::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void S_Account_List_Account::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
void S_Account_List_Account::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
void S_Account_List_Account::clear_y() {
  y_ = 0;
  clear_has_y();
}
 float S_Account_List_Account::y() const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account.y)
  return y_;
}
 void S_Account_List_Account::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:AccountPacket.S_Account_List.Account.y)
}

// -------------------------------------------------------------------

// S_Account_List

// repeated .AccountPacket.S_Account_List.Account Account_Member = 1;
int S_Account_List::account_member_size() const {
  return account_member_.size();
}
void S_Account_List::clear_account_member() {
  account_member_.Clear();
}
 const ::AccountPacket::S_Account_List_Account& S_Account_List::account_member(int index) const {
  // @@protoc_insertion_point(field_get:AccountPacket.S_Account_List.Account_Member)
  return account_member_.Get(index);
}
 ::AccountPacket::S_Account_List_Account* S_Account_List::mutable_account_member(int index) {
  // @@protoc_insertion_point(field_mutable:AccountPacket.S_Account_List.Account_Member)
  return account_member_.Mutable(index);
}
 ::AccountPacket::S_Account_List_Account* S_Account_List::add_account_member() {
  // @@protoc_insertion_point(field_add:AccountPacket.S_Account_List.Account_Member)
  return account_member_.Add();
}
 const ::google::protobuf::RepeatedPtrField< ::AccountPacket::S_Account_List_Account >&
S_Account_List::account_member() const {
  // @@protoc_insertion_point(field_list:AccountPacket.S_Account_List.Account_Member)
  return account_member_;
}
 ::google::protobuf::RepeatedPtrField< ::AccountPacket::S_Account_List_Account >*
S_Account_List::mutable_account_member() {
  // @@protoc_insertion_point(field_mutable_list:AccountPacket.S_Account_List.Account_Member)
  return &account_member_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace AccountPacket

// @@protoc_insertion_point(global_scope)
